### ISSUE TITLE
Drupal 8 and Drupal 8 Commerce Installation and settings export.

### ISSUE THREAD

**Issue by achraf-jeday** [angrycactus/social-commerce#1]
## Description

> We need to push initial code base to the repository which contains the D8 and the D8 Commerce installation and configuration.

## Acceptance Criteria

- [x] A Drupal 8 fresh install code base is pushed to the repository.
- [x] Drupal 8 Commerce module code base is pushed to the repository.
- [x] Any necessary configuration is exported in code and pushed to the repository.

## Subtasks
- [x] Setup Drupal 8 commerce module 
- [x] Export Settings
- [x] Push changes to the remote repository
- [x] Document exported settings
