### ISSUE TITLE
Determine if the Drupal 8 commerce module fits our needs

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#11]
## Description
> As a developer, I want to determine if the Drupal 8 commerce module fits our needs for current project.

## Acceptance Criteria
- [x] Link to the document that contains answers to the following questions is posted in a comment in this ticket: what is the structure of the module? what is the core features of the module? Is there any issues with the module? Is the module stable enough? If the module fits our needs?

## Subtasks
link: https://www.drupal.org/project/commerce 
- [x] Research the topic
- [x] Provide a document responding the acceptance criteria and post it in a comment in this ticket

**Comment by ihebattia** [comment]
https://docs.google.com/document/d/1ABdZa6tg8j_yw06VGbv_uFJQX8AqXC3QxrX2Ge_ysQc/edit#
