### ISSUE TITLE
Test Drupal 8 instance localy

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#12]
## Description
> As a developer, I want to be able to login to a Drupal 8 instance in my local machine.

## Acceptance Criteria
- [x] Open browser pointing to url on private IP on developer laptop
- [x] Drupal 8 login form appears
- [x] Log in with Drupal 8 super user and login successful

## Subtasks
- [x] Download the latest version of Drupal 8
- [x] Create a MySQL database and assign it to a new user
- [x] Grant all privileges to the new user on the database
- [x] Install Drupal 8 instance
- [x] Document Drupal 8 installation and post the document link in a comment in this ticket

**Comment by taiebb** [comment]
@ihebattia @achraf-jeday @willieseabrook https://docs.google.com/document/d/1XTVJQ4lXlTYOI1I6eh1kAaVrZHP0jkxi6cRN7LHEh6A/edit
