### ISSUE TITLE
Shop page theming

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#120]
## Description
> As a customer, When I open **/shop**, I want to see the shop page looks like the screenshot bellow:

![shop](https://cloud.githubusercontent.com/assets/3749521/24708033/9f962af8-1a0d-11e7-8971-1d958d5f772b.png)

## Acceptance Criteria
- [x] A breadcrumb must be displayed on the top of the shop content
- [x] The breadcrumb must displays this location: **Home -> Shop**
- [x] The title **Shop** and the **result counter** must be aligned to the left
- [x] The filters must aligned to the right
- [x] The products grid must be responsive
- [x] A test site link is posted in a comment

## Subtask
- [ ] Add margin between rows

**Comment by taiebb** [comment]
https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-175.probo.build
