### ISSUE TITLE
Update drupal modules

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#129]
## Description
> Update the following modules: commerce, views_slideshow
## Acceptance Criteria
- [x] commerce module is up to date
- [x] views_slideshow is up to date
- [x] A test site link is posted in a comment
## Subtasks
- [x] Update commerce module
- [x] Update views_slideshow module

**Comment by taiebb** [comment]
https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-132.probo.build/
