### ISSUE TITLE
Configure ProboCI

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#13]
## Description 
> As a developer,  I want to get a preview link every time I create a new pull request.

## Acceptance Criteria
Given the sub-theme is enabled, when I open the homepage with a browser, Then I should see the sub-theme displayed
- [x] Given that I created a new branch and made some changes, When I create a PR, Then I Probo should build the test site and return a preview link.
- [x] Given that all developers have access to the repository, When Probo build the test site, Then they should have access to build log et site preview.

## Subtasks
- [x] Manually upload assets to Probo.CI
- [x] Probo.Ci
  - [x] Enable and configure project settings in probo
  - [x] Modify probo.yml to use nightly backups on our staging server
- [x] Document ProboCI Setup and post a link in a comment in in this ticket

**Comment by taiebb** [comment]
https://docs.google.com/document/d/1tNIRHBRP8JwyO8VyRsh_6UHij-9TcC8r9Hl47cZfMcU/edit#
