### ISSUE TITLE
Remove frontpage welcome message

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#138]
## Description
> As a developer, I want to remove D8 welcome message from the front page.
## Acceptance criteria
- [x] The welcome messsage is removed 
- [x] A test site link is posted in a comment
## Subtasks
Go to admin/structure/views/view/frontpage, find Global: Title override link
- [x] Remove **Global: Title override (Global: Title override)**
- [x] Remove **Content: Empty Node Frontpage behavior (Content: Empty Node Frontpage behavior)**
- [x] Remove **Global: Unfiltred text (Global: Unfiltred text)**
- [x] Go to feed tab and **Disable feed**
- [x] Apply changes to **Social commerce** profile

**Comment by taiebb** [comment]
https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-139.probo.build/
