### ISSUE TITLE
Setup a Bootstrap based theme

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#14]
## Description
> As a developer, I need to be able to create a new Bootstrap sub-theme, make changes to Sass files and displaying changes without clearing the cache.

## Acceptance Criteria
- [x] Given the sub-theme is enabled, when I open the homepage with a browser, Then I should see the sub-theme displayed
- [x] Given that the twig debug is enabled, When I display the source of the page, Then I should see options like how to override a the current page.
- [x] Given that the cache is disabled, When I modify an existing twig file and refresh its related page, Then the related page should be updated without clearing the cache
- [x] Given that GulpJs and LiveReload are setup correctly, When I modify a sass file, Then a css code must be generated and the browser should reload the page automatically and displays the new changes.

## Subtasks
- [x] Install bootstrap base theme
- [x] Create a sub-theme
- [x] Disable Cache
- [x] Enable Twig Debug
- [x] Setup Gulp.js and LiveReload (check this video https://www.youtube.com/watch?v=vatnNkOKZ7o&index=4&list=PLUBR53Dw-Ef818EUxzNoWKcQ7PYUXpFFA)
- [x] Push code
- [x] Document all the process and share the link in a comment in this ticket

**Comment by taiebb** [comment]
@willieseabrook @achraf-jeday @ihebattia https://docs.google.com/document/d/1QG7gVozrmwjnqVuNAxyxv38mDJ0Oe-Bs-VFQuXzhBpc/edit
