### ISSUE TITLE
Display a breadcrumb

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#142]
## Description
> As a customer, I want to see a breadcrumb displayed in all site pages except the front page.

## Acceptance Criteria
- [x] A breadcrumb is displayed in all site pages except the front page
- [ ] A test site link is posted in a comment

## Subtasks
- [x] Install, enable and configure easy_breadcrumb module
- [x] Configure the bearded theme breadcrumb component
- [x] Apply changes to 'Social commerce' profile

**Comment by taiebb** [comment]
https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-141.probo.build/
