### ISSUE TITLE
Modify the repository to use .gitignore file.

### ISSUE THREAD

**Issue by achraf-jeday** [angrycactus/social-commerce#16]
## Description
> We need to use .gitignore file to exclude some files and folders when we are pushing code to the repository.

## Acceptance Criteria

- [x] A .gitingnore file should be pushed to the repository root folder.
- [x] non-code files and folders should be excluded.

## Subtasks
- [x] Rename example.gitignore to .gitignore
- [x] Remove ignored files and folders
