### ISSUE TITLE
Checkout process theming

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#196]
## Description

> As a customer, When I do the checkout workflow as either a guest or logged in user, i want it look fundamentally reasonable

## Acceptance Criteria
- [x] Add product to cart
- [x] Go to /cart
- [x] Click checkout e.g /checkout/3/login
- [x] Returning user process looks good
- [x] Guest process looks good

## Subtasks
- [x] Default payment gateway is added ticket commerce_cop depends #238 and #239
- [x] Order Summary table is fixed
- [x] A margin between "Continue to review" button and payment information box is increased
- [x] Order total is moved under Order summary table
- [x] The page must be responsive
- [x] A test site link is posted in a comment

**Comment by achraf-jeday** [comment]
Test site:

https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-267.probo.build
