### ISSUE TITLE
Setup remote server

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#2]
## Description

> As a developer, I want to have a fresh installation of Drupal 8 instance deployed to the test server.
## Acceptance Criteria
- [x] Load a web browser at a public URL and see a login page https://bearded.angrycactus.biz
- [x] Login as drupal user 1
- [x] List of test usernames and roles is available in a LastPass entry.

## Sub-tasks
- [x] Deploy a digital ocean Ubuntu server 14.04 machine
- [x] Setup LAMP (check Drupal 8 configuration)
- [x] Setup SSH
- [x] Setup the follwoing sub-domain: bearded.angrycactus.biz
- [x] Forward developers SSH keys to the remote server
- [x] Forward remote server SSH key to the Github Repository
- [x] Setup MySQL server
- [x] Create a database and a user for the Drupal 8 instance
- [x] Deploy a fresh Drupal 8 instance
- [x] Document usernames and passwords in a LastPass entry.
- [x] Setup Zsh
- [x] Document setup remote server steps and past a link for doc in a comment in this ticket

**Comment by taiebb** [comment]
https://docs.google.com/document/d/1LN24ZnXLpfPDVWXToViUZsfJKwmmxtJNeLYsVRE0IVA/edit#
