### ISSUE TITLE
Automating Stage backups and updating ProboCI

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#20]
## Description
> As a developer, I want to make a nightly databases and files backups from the staging server.

## Acceptance Criteria
- [x] The database of bearded.angrycactus.biz is dumped nightly
- [x] The database is uploaded to ProboCi nightly
- [x] A files tar.gz archive of bearded.angrycactus.biz is dumped nightly
- [x] The files tar.gz is uploaded to probo nightly
- [x] Given that the site is deployed, When I open http://social-commerce.angrycactus.biz, Then I should see the website up and running

## Subtasks
- [x] Create a job to perform a nightly database backup
- [x] Create a job to perform a files backup
- [x] Setup Probo Uploader on the staging server
- [x] Make script to push database + files to ProboCi
- [x] Change website url to http://social-commerce.angrycactus.biz
- [x] Create a deployment job
