### ISSUE TITLE
Fix breadcrumb displaying

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#226]
## Description
> As a developer, I want to fix the Breadcrumb displaying.

## Acceptance Criteria
- [x] When I open **/product/1**, I should see the breadcrumb displayed like: Home > Shop > [ProductName]
- [x] A site test link is posted in a comment

## Subtasks
- [x] Remove easy_breadcrumb module
- [x] Configure bootstrap theme breadcrumb

**Comment by taiebb** [comment]
https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-270.probo.build/
