### ISSUE TITLE
Deploy the bearded theme

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#23]
## Description
> As a developer, I want to deploy the beaded theme when installing the social commerce profile.

## Acceptance Criteria
- [x] Given that the the social_commerce profile is deployed, when I open /, Then I should see the bearded theme enabled and the logo is set.
- [x] A test site link is provided in a comment 
- [x] Link to the document containing the result of the research is posted in a comment in this ticket

## Subtasks
- [x] Research
- [x] Set the bearded theme as a default theme
- [x] Change the theme logo
- [x] Create a document for the search result and post is a comment in this ticket.

**Comment by ihebattia** [comment]
https://docs.google.com/document/d/1ghw5s73AoKbYSlQD05E_sE1tmkPxOolCkOmOHq3KoPk/
