### ISSUE TITLE
Launch marketing site

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#231]
## Description
> As a product owner, I want to see a mock-up of the landing page in order to get idea about the theme before it is created.

## Acceptance Criteria
**Inspiration links :** http://getdkan.com/ , http://pages.revox.io/frontend/1.1.0/html/01/, http://demo.web3canvas.com/themeforest/startupkit/index-webapp.html, http://demo.web3canvas.com/themeforest/all-in-one/base.html, http://preview.themeforest.net/item/stylio-responsive-html5-app-landing-page/full_screen_preview/6535447?_ga=2.149803893.291213730.1494866589-885761476.1489429429

- [ ] The theme must have the following regions: header, Join community, Features, commercial support, Test drive and a footer
- [ ] The header must contain a logo, a menu and a hero section
- [ ] Join community must contains 3 boxes: every box contains an icon + description + link
- [ ] Features must contains: Intro text, 3 screenshot accompanied by a description
- [ ] Commercial support must contains: an intro text and link to Drupal marketplace
- [ ] Test drive must contains: a title, intro text, a box(image + link)
- [ ] The footer must contains: links, social icons and a copyright
- [ ] A screenshot of the mock-up is posted in a comment

## Tasks

- [x] Choose base theme
- [x] First iteration with lorem ipsum and correct structure
- [x] Second iteration with draft content
- [ ] Final draft
- [ ] Register domain name and publish

**Comment by willieseabrook** [comment]
@taiebb @ihebattia should be assigned this to deploy to AWS S3 + Cloud Front
