### ISSUE TITLE
SPIKE: Simplytest.me Discovery

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#234]
## Description
> As a developer, I want to know how to host the social commerce distribution on Drupal.org or https://simplytest.me in order to create a free demo for customers.

## Acceptance Criteria
- [x] Review https://simplytest.me/qa

## Subtask
- [x] Investigate https://simplytest.me/ build process / developer docs
- [x] Create a drupal.org sandbox based on master
- [x] Test whether distribution builds on simplytest.me
- [x] Test whether we need to do custom make file for simplytest.me
