### ISSUE TITLE
Create a social commerce free demo 

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#235]
## Description
> As a developer, I want to host a free social commerce distribution demo in order that customers can test it.

## Acceptance Criteria
- [ ] A search result document is posted in a comment
- [ ] The document is reviewed by Willie

## Subtask
- [ ] Investigate Pantheon features, pricing and hosting process
- [ ] Investigate Acquia features, pricing and hosting process
- [ ] Choose a platform
- [ ] Create a tutorial on how to create a free demo
