### ISSUE TITLE
SPIKE: Publishing a Drupal 8 distribution on Drupal.org

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#236]
Timebox: 1 hour

## Description
> As a developer, I want to know how to publish a Drupal 8 distribution on Drupal.org.

## Acceptance Criteria
- [x] Any important notes are pasted as a comment
- [x] Read drupal.org documentation

## Subtask
- [x] Have Riadh test his authorized account
- [x] Create a sandbox project with a copy and paste of the latest github master

**Comment by ihebattia** [comment]
Create Distribution project : https://www.drupal.org/node/add/project-distribution
Sandbox project : https://www.drupal.org/sandbox/ihebattia/2879856
Documentation : https://www.drupal.org/docs/develop/packaging-a-distribution/how-to-package-a-distribution-on-drupalorg#release
