### ISSUE TITLE
Purchase a product using a payment method

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#238]
## Related

#239 Spike ticket

## Description
> As a customer, I want to purchase a product using a payment method.

## Acceptance Criteria
- [x] Add product to cart
- [x] Go to checkout
- [ ] See an option for the payment method, choose it
- [x] Click buy it works

## Subtasks
- [x] Install probably commerce_cop if not commerce_stripe (depends on #239)
- [x] Configure it
- [x] Test it
- [x] Export config
