### ISSUE TITLE
Create new brands

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#244]
## Description
> As an anonymous user, when I open **/**, I want to see four new brands displayed in **Our brands** section.

## Acceptance Criteria
- [x] The four brands names mustn't exist as a real brand
- [ ] A site test link in posted on a comment

## Subtasks
- [x] Design four brands 
- [ ] Add them to the site
- [ ] Export config
