### ISSUE TITLE
Deploy a custom slideshow module

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#25]
## Description
> As a developer, I want to deploy a custom slideshow module when installing the social commerce profile using probo.Ci.

## Acceptance Criteria
- [x] Given that the social_commerce profile is deployed, when I open /, Then I should see the slideshow displayed and populated with 3 items. 
- [x] A test site link is provided in a comment 
- [x] Link to the document containing the result of the research is posted in a comment in this ticket

## Subtasks
- [x] Search and choose a slideshow module
- [x] Setup the slideshow
- [x] Create a custom content type (image, text, link)
- [x] Populate the slideshow with 3 items
- [x] Create a document for the search result and post is a comment in this ticket.

**Comment by achraf-jeday** [comment]
Test site (digital ocean) :

**Comment by achraf-jeday** [comment]
Documentation link:

https://docs.google.com/document/d/1hA77Zvelt9ZVVMUFuDkVSp6DuJG76SHzkvfPolFQ7gs/edit#
