### ISSUE TITLE
Have a stable demo site based on master

### ISSUE THREAD

**Issue by willieseabrook** [angrycactus/social-commerce#259]
## Description
> As a potential user, I need to see the distribution functioning so I can understand its features.

## Acceptance Criteria
- [x] Credentials are added to Lastpass
- [x] URL is demo.social-commerce.angrycactus.biz
- [x] Site rebuilds every 24 hours based on master

## Subtasks
- [x] Add credentials to Lastpass
- [x] Deploy new VPS dedicated to social commerce
- [x] Configure rundeck

**Comment by taiebb** [comment]
http://demo.social-commerce.angrycactus.biz/
