### ISSUE TITLE
Drupal 8 Unit Testing

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#27]
## Description 
> As a developer, I want to learn how to make unit testing in Drupal 8.

## Acceptance Criteria
- [x] Link to documentation is posted in a comment in this ticket

## Subtasks
- [x] Research the subject
- [x] Create a module with a single function
- [x] Create a the unit test for the function
- [x] Run the unit test 
- [x] Document all the steps and post a link in a comment in this ticket

**Comment by achraf-jeday** [comment]
Link to documentation:

https://docs.google.com/document/d/1piFo-Y2rNM21yZuiTNQP5OoAhmWWZLDobmZPxgQ47rY/edit
