### ISSUE TITLE
Drupal 8 Behat testing

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#28]
## Description 
> As a developer, I want to learn how to make Behat testing in Drupal 8.

## Acceptance Criteria
- [x] Link to documentation is posted in a comment in this ticket

## Subtasks
- [x] Research the subject
- [x] Create the following Behat test: In order to verify admin page access, As an administrator user, I need to login as administrator
- [x] Run the Behat test 
- [x] Document all the steps and post a link in a comment in this ticket

**Comment by achraf-jeday** [comment]
Link to the documentation:

[https://docs.google.com/document/d/1GP2ufqFqYbrHhXUuXPlh2nMMn2i_Kr5HflQsuFtw28E/edit](https://docs.google.com/document/d/1GP2ufqFqYbrHhXUuXPlh2nMMn2i_Kr5HflQsuFtw28E/edit)
