### ISSUE TITLE
Host marketing website on AWS

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#289]
## Description
> As a product owner, I want the marketing site hosted on AWS.

## Acceptance Criteria
- [x] A site link is posted in a comment

## Subtasks
- [x] Buy the domain name
- [x] Configure domain dns to point to AWS hosting
- [x] Create two Cloud front on AWS
- [x] Create two S3 buckets

**Comment by ihebattia** [comment]
social-commerce.info
