### ISSUE TITLE
Deploy book module

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#29]
## Description
> As a developer, I want to deploy the Drupal 8 'Book' core module when I install social_commerce profile using probo.Ci.

## Acceptance Criteria
- [x] Given that the social_commerce profile is deployed, when I open /admin/modules, Then I should see the 'book' module enabled
- [x] Given that the custom profile is deployed, When I open /admin/people, Then I should see a new user called 'test' is added, enabled and set as administrator
- [x] A test site link is provided in a comment 
## Subtasks
- [x] Create an empty installation profile
- [x] Update the installation profile to make it enable the core module 'Book'
- [x] Update the installation profile to make it add a new user called 'test'
- [x] Push the code to the remote repository
- [x] Update probo.Ci to make it install the new profile

**Comment by taiebb** [comment]
Test site link: https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-37.probo.build/
