### ISSUE TITLE
Update website automatically

### ISSUE THREAD

**Issue by willieseabrook** [angrycactus/social-commerce#302]
## Description
> As a website editor I want code changes automatically deployed to cloudfront

## Acceptance Criteria
- [ ] git clone marketing site
- [ ] Edit a file and push
- [ ] Rundeck job is triggered
- [ ] Cloudfront website http://www.social-commerce.info is updated

## Subtasks
- [ ] Create Git repo & load website code
- [ ] Install rundeck vm for testing
- [ ] Test git clone
- [ ] Test s3 put of new code
- [ ] Test aws cloudfront update-distribution?

**Comment by taiebb** [comment]
@achoura Please review this ticket and assigned back to @ihebattia.
