### ISSUE TITLE
Add site header

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#50]
## Description
> As a customer, I want to see the header displayed.

## Acceptance Criteria
- [x] Given the sub-theme is enabled, when I open the homepage with a browser, Then I should see the sub-theme displayed
- [x] A 'Not Just Moustache' slogan is displayed in the header
- [x] A principal menu is displayed in the header
- [x] a shpping cart in placed in the header
- [x] a socondary menu is displayed the header
- [x] A test site link is posted in a comment

## Subtasks
- [x] Add 'Not Just Moustache" as a slogan
- [x] Add a principal menu with the following empty links (Home, Contact, Shop) and place it in the header
- [x] Place Shopping cart block in header
- [x] Add a secondary menu and place it in the header
- [x] Apply changes to 'Social commerce' profile
