### ISSUE TITLE
Add slideshow

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#52]
## Description
> As a customer, I want to see a slideshow displayed in the homepage under the site header.

## Acceptance Criteria
- [x] Given that the social_commerce profile is deployed, when I open /, Then I should see the slideshow displayed under the header and populated with 3 items
- [x] A test site link is provided in a comment

## Subtasks
- [x] Create a a slideshow region under the header region
- [x] Place the already created slideshow in the slideshow region
- [x] Apply changes to 'Social commerce' profile
- [x] Remove slideshow items from homepage.

**Comment by achraf-jeday** [comment]
Test Site:

https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-65.probo.build/
