### ISSUE TITLE
Add a call to action banner

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#53]
## Description
> As a customer, I want to see a call to action banner displayed under the slideshow.

## Acceptance Criteria
- [x] Given that the social_commerce profile is deployed, when I open /, Then I should see the call to action banner displyed under the slideshow
- [x] A test site link is provided in a comment

## Subtasks
- [x] Create a 'call to action banner' region
- [x] Create a 'call to action banner' Block
- [x] Place the 'call to action banner' block in the 'call to action' region
- [x] Apply changes to 'Social commerce' profile

**Comment by achraf-jeday** [comment]
Test site :

https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-66.probo.build/
