### ISSUE TITLE
Display random products

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#54]
## Description
> As a customer, I want to see 4 random products displayed under the call to action banner.

## Acceptance Criteria
- [x] Given that the 'social_commerce' profile is deployed, when I open /, Then I should see 4 products displayed randomly under 'Call to action banner'
- [x] Every product must have a title, image, price, a link to view the product details and a category
- [x] A test site link is provided in a comment

## Subtasks
- [x] Add a new store
- [x] Add 'Tunisian Dinar' currency
- [x] Add a category
- [x] Add 8 products
- [x] Create a custom view (displays 4 random products as a Grid from the early created category, Export to a block called 'Random products') 
- [x] Create a region 'Random products' 
- [x] Place Block 'Random products' in 'Random products' region under 'Call to action banner'
- [x] Apply changes to 'Social commerce' profile
