### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#59]
## Description
> As a customer, I want to see the footer displayed at the bottom of the page.

## Acceptance Criteria
- [x] Given the sub-theme is enabled, when I open the homepage with a browser, Then I should see the footer displayed.
- [x] A 'Credit' block is displayed inside the footer
- [x] A 'Links' block is displayed inside the footer
- [x] A 'Social media' block is displayed inside the footer
- [x] A 'Copyright' block is displayed inside the footer
- [x] A test site link is posted in a comment

## Subtasks
- [x] Add a region called 'Footer' under 'Random products' region
- [x] Add a block 'Credits' with a random text in it
- [x] Add block 'Links' with main menu links
- [x] Add block 'Copyright' under block 'links'
- [x] Apply changes to 'Social commerce' profile
