### ISSUE TITLE
Add our clients brands

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#61]
## Description
> As a customer, I want to see the our clients brands displayed under Random products.

## Acceptance Criteria
- [x] Given the sub-theme is enabled, when I open the homepage with a browser, Then I should see the our clients brands displayed.
- [x] A test site link is posted in a comment

## Subtasks
- [x] Create a new content type 'our clients' (title, image, link)
- [x] Create a custom view 'our clients' that displays the 'our clients' content type as a grid
- [x] Apply changes to 'Social commerce' profile
