### ISSUE TITLE
Add Shop page

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#69]
## Description
> As a customer, when I open /shop, I want to see a shop page that displays a list of products.

## Acceptance Criteria
- [x] Given the social commerce profile is installed, when I open the /shop with a browser, Then I should see a list of products displayed.
- [x] Counters displaying the total number of products and the number of the current page
- [x] A filter by date
- [x] A filter by order(Asc, Desc)
- [x] A pagination feature
- [x] Displays 4 products per page
- [x] A test site link is posted in a comment

## Subtasks
- [x] Create a view called "Shop" from product content
- [x] Display the title, image, price, path to product details, an add to cart link and the category of the product
- [x] Displays 4 products per page
- [x] Apply changes to 'Social commerce' profile

**Comment by ihebattia** [comment]
https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-99.probo.build/shop
