### ISSUE TITLE
Add product details page

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#70]
## Description
> As a customer, when I click on a product, I want to see the details of the product.

## Acceptance Criteria
- [x] Given the social commerce profile is installed, when I open the click on a product, Then I should see the details of the product.
- [x] The product must have the following fields displayed: title, price, image, description, category
- [x] A test site link is posted in a comment

## Subtasks
- [x] Display the title, image, price, description, an add to cart link and the category of the product
- [x] Apply changes to 'Social commerce' profile
