### ISSUE TITLE
Related Products

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#71]
## Description
> As a customer, in the product details page, I want to see a list of related products displayed under the product details.

## Acceptance Criteria
- [x] Given the social commerce profile is installed, when I open the click on a product, Then I should see a list of related products displayed under the product details.
- [x] The product must have the following fields displayed: title, price, image, category
- [x] Displays maximum 8 products
- [x] The related products block is displayed only in product details page
- [x] A test site link is posted in a comment

## Subtasks
- [x] Create a view called "Related product" from the current product category and export it as a block
- [x] Display the title, image, price, path to product details, an add to cart link and the category of the product
- [x] Displays max 8 products
- [x] Place the block in content region under product details
- [x] Ensure that related products is only displayed in product details page
- [x] Apply changes to 'Social commerce' profile

**Comment by achraf-jeday** [comment]
Test Site:

https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-284.probo.build/
