### ISSUE TITLE
Add a Product Category block

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#72]
## Description
> As a customer, in the product details page, I want to see a list of related products displayed under the product details.

## Acceptance Criteria
- [ ] Given the social commerce profile is installed, when I open the click on a product, Then I should see a list of product categories names displayed in the sidebar.
- [ ] 4 product categories are displayed
- [ ] A test site link is posted in a comment

## Subtasks
- [ ] Create a sidebar region
- [ ] Create a view called "Product Category" from the product types
- [ ] Export the view as a block and put it in the sidebar region
- [ ] Display only the name of the product type
- [ ] Displays maximum 4 product categories
- [ ] Apply changes to 'Social commerce' profile
