### ISSUE TITLE
Add Latest Products block

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#73]
## Description
> As a customer, in the product details page, I want to see a list of latest products displayed in the sidebar under Product Category.

## Acceptance Criteria
- [x] Given the social commerce profile is installed, when I open the click on a product, Then I should see a list of related products displayed under the product details.
- [x] Only 4 products are displayed
- [x] The "latest products" block is displayed under "Product category" block in the sidebar region
- [x] A test site link is posted in a comment

## Subtasks
- [x] Create a view called "Latest products" from the product content
- [x] Display only the image, title and price of the product
- [x] Displays only 4 products
- [x] Export the view to a block
- [x] Place the block under Product Category block in the sidebar region
- [x] Apply changes to 'Social commerce' profile

**Comment by taiebb** [comment]
[https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-95.probo.build/](url)
