### ISSUE TITLE
Experiment with Drupal 8 Panels module

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#77]
## Description
> As a developer, I want to test if D8 Panels modules can create a customized layouts for multiple pages.

## Acceptance Criteria
- [ ] A site site link is provided in a comment i nthis ticket

## Subtasks
- [ ] Research the subject
- [ ] Install the [module](https://www.drupal.org/project/panels) 
- [ ] Create a front page with a header, content, sidebar and a footer region
- [ ] Assign 2 blocks to sidebar region in the front page
- [ ] Create a second page 'About us' with a header, content, sidebar and a footer region
- [ ] Assign 2 diffenrents blocks to sidebar region in 'About us' page
