### ISSUE TITLE
Add information blocks

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#85]
## Description
> As a customer, I want to see 'Why Choose Us?', 'Who We Are?' and 'What We Do?' blocks displayed only on the front page.

## Acceptance Criteria
- [x] Given the social commerce profile is installed, when I open the homepage with a browser, Then I should see 'Why Choose Us?', 'Who We Are?' and 'What We Do?' blocks displayed.
- [x] A test site link is posted in a comment

## Subtasks
- [x] Add the following regions to the bearded theme:  topwidget_first,  topwidget_second and topwidget_third
- [x] Add a block 'Why Choose Us?'
- [x] Add block 'Who We Are?'
- [x] Add block 'What We Do?'
- [x] Apply changes to 'Social commerce' profile

**Comment by taiebb** [comment]
https://1be29c17-f911-402f-bd36-bb1966b11cc4--pr-87.probo.build/
