### ISSUE TITLE
Determine which Css Framework to use

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#9]
## Description
> As a developer, I need to determine which CSS Framework to use for Drupal8 commerce website.

## Acceptance Criteria
- [x] Link to comparison document is posted in a comment in this ticket

## Subtasks
- [x] Research and compare between Bootstrap and Foundation
- [x] Document the comparison and post the document in a  comment in this ticket

**Comment by taiebb** [comment]
@achraf-jeday @willieseabrook @iheb https://docs.google.com/document/d/1JiVRp-_k08v9uPxkzAKDzusUjiitWgvq2cHsAHcyGIw/edit#
