### ISSUE TITLE
Configuration sync directory setup

### ISSUE THREAD

**Issue by taiebb** [angrycactus/social-commerce#93]
## Description
> As a developer, I want to setup the configuration sync directory, so that I can share CM with other developers.

## Acceptance Criteria
- [x] Given that the configuration sync directoru is already setup, when I open the [project repository](https://github.com/angrycactus/social-commerce), Then I should see the following structure:
- **/drupal_root/config/sync** // Not web accessible
- **/drupal_root/test**s // Drupal tests
- **/drupal_root/docroot** // Drupal source, web accessible
- [x] A ProboCi test site link is posted in a comment

## Subtasks
- [x] Create **/drupal_root/docroot** and put into it all drupal folders and files
- [x] Change CM folder location to **/drupal_root/config/sync**
- [x] Make necessary changes to **settings.php**
- [x] Create **/drupal_root/tests** folder
- [x] Update ProboCi configuration in order to match the new structure modifications
- [x] Create a PR and post a test link in a comment in this ticket

**Comment by taiebb** [comment]
[https://app.probo.ci/#/dashboard/build/91874d28-6b6a-4d4a-91ff-6089adf7953f/task/56c6b6647e000000](url)
